language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# install python dependencies including this package in the travis
# virtualenv
install:
  - pip install -r requirements/python-dev
  - python -m textblob.download_corpora

# commands to run the testing suite. if any of these fail, travic lets us know
script:
  - nosetests --with-coverage --cover-package=scrubadub
  - pep8 scrubadub/
  - cd docs && make html && cd -

# commands to run after the tests successfully complete
after_success:
  - coveralls
